title: BloxFresh Support
description: Support for BloxFresh
baseurl: "/"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  Group: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

remote_theme: just-the-docs/just-the-docs
